# Directory paths
RAW_DATA_DIRECTORY: raw_data
PROCESSED_DATA_DIRECTORY: processed_data
RAW_DATA_BACKGROUND_DIRECTORY: raw_data_background
PROCESSED_DATA_BACKGROUND_DIRECTORY: processed_data_background

# Evaluation data files
eval_data_files:
  - test_qX_qWY_qqqlv_X200_Y60.npz
  - test_qX_qWY_qqqlv_X250_Y80.npz
  - test_qX_qWY_qqqlv_X300_Y100.npz
  - test_qX_qWY_qqqlv_X350_Y130.npz
  - test_qX_qWY_qqqlv_X400_Y160.npz

# Data structure parameters
DECAY_CHAIN: ["P1"]
N_PARTICLES: 4
N_FEATURES: 6
MET_IDS: [12]
LEPTON_IDS: [11]
TRAIN_TEST_SPLIT: 0.2
SCALABLE_FEATURES: [0, 1, 2]

GNN_BASELINE_F_R_LAYER_SIZES: [96, 64, 32]
GNN_BASELINE_F_O_LAYER_SIZES: [128, 64, 32]
GNN_BASELINE_PHI_C_LAYER_SIZES: [16, 8, 4]
GNN_BASELINE_LEARNING_RATE: 0.0005
GNN_BASELINE_EARLY_STOPPING_PATIENCE: 6
GNN_BASELINE_REDUCE_LR_PATIENCE: 2

GNN_TRANSFORMED_LEARNING_RATE: 0.0005
GNN_TRANSFORMED_LEARNING_RATE_DECAY: 0.9

SIAMESE_PHI_C_LAYER_SIZES: [16]
SIAMESE_PROJ_HEAD_LAYER_SIZES: [24, 32]
SIAMESE_LEARNING_RATE: 0.0001

DOWNSTREAM_FREEZE_EPOCH: 3
DOWNSTREAM_LEARNING_RATE: 0.000005
DOWNSTREAM_FROZEN_LEARNING_RATE: 0.0001
DOWNSTREAM_LR_DECAY: 0.90

DOWNSTREAM_NO_FINETUNE_LEARNING_RATE: 0.0001
DOWNSTREAM_LAYER_SIZES: [8, 4]

BATCHSIZE: 128
EPOCHS: 20
SIAMESE_EPOCHS: 30
SIMCLR_LOSS_TEMP: 0.1

RUN_ID: 3
DATASET_NAME: ""
