# Directory paths
RAW_DATA_DIRECTORY: raw_data_set2
PROCESSED_DATA_DIRECTORY: processed_data_set2
RAW_DATA_BACKGROUND_DIRECTORY: raw_data_background_set2
PROCESSED_DATA_BACKGROUND_DIRECTORY: processed_data_background_set2

# Evaluation data files
EVAL_DATA_FILES:
  - test_bA_bgX_bgqqqqY_bgqqqqqqqqlv_A2500_X1000_Y500.npz
  - test_bA_bgX_bgqqqqY_bgqqqqqqqqlv_A3300_X1400_Y550.npz
  - test_bA_bgX_bgqqqqY_bgqqqqqqqqlv_A4100_X1800_Y600.npz
  - test_bA_bgX_bgqqqqY_bgqqqqqqqqlv_A5300_X2400_Y800.npz
  - test_bA_bgX_bgqqqqY_bgqqqqqqqqlv_A6500_X3000_Y1000.npz

# Data structure parameters
DECAY_CHAIN: ["P1", "P2"]
N_PARTICLES: 12
N_FEATURES: 7
MET_IDS: [12]
LEPTON_IDS: [11]
GLUON_IDS: [21]
TRAIN_TEST_SPLIT: 0.2
SCALABLE_FEATURES: [0, 1, 2]

GNN_BASELINE_F_R_LAYER_SIZES: [96, 64, 32]
GNN_BASELINE_F_O_LAYER_SIZES: [128, 96, 64]
GNN_BASELINE_PHI_C_LAYER_SIZES: [16, 8, 4]
GNN_BASELINE_LEARNING_RATE: 0.0005
GNN_BASELINE_EARLY_STOPPING_PATIENCE: 6
GNN_BASELINE_REDUCE_LR_PATIENCE: 2

GNN_TRANSFORMED_LEARNING_RATE: 0.0005
GNN_TRANSFORMED_LEARNING_RATE_DECAY: 0.9

SIAMESE_PHI_C_LAYER_SIZES: [32]
SIAMESE_PROJ_HEAD_LAYER_SIZES: [48, 64]
SIAMESE_LEARNING_RATE: 0.0001

DOWNSTREAM_FREEZE_EPOCH: 3
DOWNSTREAM_LEARNING_RATE: 0.000005
DOWNSTREAM_FROZEN_LEARNING_RATE: 0.0001
DOWNSTREAM_LR_DECAY: 0.90
DOWNSTREAM_NO_FINETUNE_LEARNING_RATE: 0.0001
DOWNSTREAM_LAYER_SIZES: [16, 8]

BATCHSIZE: 256
EPOCHS: 15
SIAMESE_EPOCHS: 30
SIMCLR_LOSS_TEMP: 0.1

RUN_ID: 1
DATASET_NAME: "_set2"
